version: "3"

services:
  create:
    # 현재 디렉토리의 Dockerfile을 사용하여 이미지 빌드
    build: .
    # 컨테이너 이름 설정
    container_name: rag-create-collection
    # 호스트의 현재 디렉토리를 컨테이너의 /app 디렉토리에 마운트
    volumes:
      - ./db:/app/db # db 폴더를 컨테이너 내부의 /app/db에 마운트
    # 컨테이너가 종료되어도 자동으로 다시 시작하지 않음
    restart: "no"
    # 컨테이너 시작 시 실행할 명령어 설정
    command: python create_collection.py

  query:
    # 현재 디렉토리의 Dockerfile을 사용하여 이미지 빌드
    build: .
    # 컨테이너 이름 설정
    container_name: rag-query-collection
    # 호스트의 현재 디렉토리를 컨테이너의 /app 디렉토리에 마운트
    volumes:
      - ./db:/app/db # db 폴더를 컨테이너 내부의 /app/db에 마운트
    # 컨테이너가 종료되어도 자동으로 다시 시작하지 않음
    restart: "no"
    # 컨테이너 시작 시 실행할 명령어 설정
    command: python query_collection.py
